### ISSUE TITLE
Would an armhf / armv7 Docker container be possible

### ISSUE THREAD

**Issue by azurefreecovid** [pitkley/dfw#289]
Hi there,

I'm really enjoying using DFW and I was wondering if it would be possible to have a ``armv7`` build added to Docker hub?

Cheers,

**Comment by pitkley** [comment]
Hi @azurefreecovid. Thank you very much for this suggestion, I'm very interested in it.

I'll try to look into this as soon as I find the time, although given that I have no prior experience in building Docker images for additional architectures, don't expect a result too quickly.

If you have any knowledge or even code you'd like to share, I'd appreciate it -- and a pull request is always welcome, too!

**Comment by opencloudengineer** [comment]
@pitkley Mind if I work on it?

**Comment by pitkley** [comment]
Sorry for not getting back to you earlier, @opencloudengineer. Of course, please, go right ahead! I'm happy to review any contributions and will gladly help with any setup that might be required on the Docker Hub side, if there is any!

**Comment by opencloudengineer** [comment]
Thanks, but I have no experience with Rust so I will have to look into building binaries with cargo for different architectures. I'll ping you if I face any problem with that.

BTW, I have never used Docker Hub Registry, except for docker pull, but I don't think that'll be a problem.

Also I was wondering, how about using GHCR as registry along with docker hub, you know due to docker hub [rate limits](https://www.docker.com/increase-rate-limits).
As [GitHub Container Registry supersedes the existing Packages Docker registry](https://docs.github.com/en/packages/guides/migrating-to-github-container-registry-for-docker-images) that you are already using.

**Comment by pitkley** [comment]
@azurefreecovid  good news, this is now implemented. The Docker image is now built for `amd64`, `arm64` and `armv7` (specifically `armhf`). You can get it both from Docker Hub and GHCR:

* `pitkley/dfw:main` - https://hub.docker.com/r/pitkley/dfw/tags?page=1&name=main
* `ghcr.io/pitkley/dfw:main` - https://github.com/pitkley/dfw/pkgs/container/dfw/14529898?tag=main

The next release of DFW which will be pre-built for the mentioned architectures will be v1.3.0, which I expect I will release in about a week's time.
